name: Deploy to Azure App Service (STAGING)

on:
  push:
    branches:
      - qa/fix-venue-bleed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure App Service (qaconcierge slot)
        uses: azure/webapps-deploy@v3
        with:
          app-name: wc-concierge-app
          slot-name: qaconcierge
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8A2A21DD8C1746F8B82DD8ADDA565F8F }}
          package: .